;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Ошибка
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[FRAME_ERROR]
position = 233,228,566,370
color = 255,128,128,128
command = click
command = deactivate,event:HideError

[FADER_ERROR]
position = -134,-1,933,600
leftColor = 150,0,0,0
topColor = 150,0,0,0
rightColor = 150,0,0,0
bottomColor = 150,0,0,0
borderColor = 0,0,0,0

[TEXT_ERROR]
position = 272,258,527,322
fontScale = 0.97
lineSpace = 16
alignment = center

[OK_BUTTON_ERROR]
bBreakCommand = 1
command = click,event:HideError
command = deactivate,event:HideError
command = activate,event:HideError
position = 328,327,471,361
string = Ok
glowoffset = 0,0
