[IMAGE]
RelativePosX = 0.9
RelativePosY = 0.843
RelativeWidth = 0.12
RelativeHeight = 0.12
HorisontalFramesCount = 8
VerticalFramesCount = 8

[TIPS]
font = interface_normal
lineSpace = 50
;     = 0xFFFFFFFF
color = 4294967295
scale = 2.5
RelativePosX = 0.5
RelativePosY = 0.865
RelativeWidth = 0.5
