[MAIN]
item = 1,RECTANGLE,MOUSE_BLOCKER
item = 10,RECTANGLE,DIALOG_BACK
item = 20,FRAME,DIALOG_FRAME
item = 25,PICTURE,LEFT_PORTRAIT
item = 25,PICTURE,RIGHT_PORTRAIT
item = 28,PICTURE,LEFT_NATION
item = 28,PICTURE,RIGHT_NATION
item = 30,FRAME,LEFT_ACTIVE
item = 30,FRAME,RIGHT_ACTIVE
item = 35,RECTANGLE,LEFT_SHADE
item = 35,RECTANGLE,RIGHT_SHADE
item = 40,FORMATEDTEXT,LEFT_NAME
item = 40,FORMATEDTEXT,RIGHT_NAME
item = 50,FORMATEDTEXT,DIALOG_TEXT

[MOUSE_BLOCKER]
position = 0,0,800,600
leftColor = 0,0,0,0
topColor = 0,0,0,0
rightColor = 0,0,0,0
bottomColor = 0,0,0,0
borderColor = 0,0,0,0
bShowGlowCursor = 0

[DIALOG_BACK]
position = 10,466,790,599
leftColor = 225,15,12,9
topColor = 225,15,12,9
rightColor = 225,15,12,9
bottomColor = 225,15,12,9
borderColor = 0,0,0,0
bShowGlowCursor = 0

[DIALOG_FRAME]
position = 10,466,790,599
captionheight = 0
captiondividerheight = 0
bShowGlowCursor = 0

[LEFT_PORTRAIT]
position = 15,476,111,572
groupName = FACE128_0
picName = face
bShowGlowCursor = 0

[RIGHT_PORTRAIT]
position = 689,476,785,572
groupName = FACE128_0
picName = face
bShowGlowCursor = 0

; Герб нации в нижнем углу портрета
[LEFT_NATION]
position = 89,548,113,572
groupName = NATION_ICONS
picName = Pirate
bShowGlowCursor = 0

[RIGHT_NATION]
position = 763,548,787,572
groupName = NATION_ICONS
picName = Pirate
bShowGlowCursor = 0

[LEFT_ACTIVE]
position = 13,474,113,574
captionheight = 0
captiondividerheight = 0
bShowGlowCursor = 0

[RIGHT_ACTIVE]
position = 687,474,787,574
captionheight = 0
captiondividerheight = 0
bShowGlowCursor = 0

[LEFT_SHADE]
position = 15,476,111,572
leftColor = 165,0,0,0
topColor = 165,0,0,0
rightColor = 165,0,0,0
bottomColor = 165,0,0,0
bShowGlowCursor = 0

[RIGHT_SHADE]
position = 689,476,785,572
leftColor = 165,0,0,0
topColor = 165,0,0,0
rightColor = 165,0,0,0
bottomColor = 165,0,0,0
bShowGlowCursor = 0

[LEFT_NAME]
position = 15,575,111,595
font = interface_normal
fontScale = 0.70
lineSpace = 16
alignment = center
Color = 255,225,210,175
bShowGlowCursor = 0

[RIGHT_NAME]
position = 689,575,785,595
font = interface_normal
fontScale = 0.70
lineSpace = 16
alignment = center
Color = 255,225,210,175
bShowGlowCursor = 0

[DIALOG_TEXT]
position = 125,480,675,548
font = interface_normal
fontScale = 0.78
lineSpace = 16
alignment = left
Color = 255,245,240,220
bUseWheel = 0
bShowGlowCursor = 0
